[package]
name = "splice-daemon"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "splice-daemon"
path = "src/main.rs"

[dependencies]
splice-core = { workspace = true }
splice-platform = { workspace = true }
splice-tailscale = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
